import '../../classes/calendar_class.dart';

/// Short alias for FeastDates to allow for a readable const Map.
class F extends FeastDates {
  const F(int m, int d, int p) : super(month: m, day: d, precedence: p);
}

/// General Roman Calendar - Fixed Dates
const Map<String, FeastDates> commonFeastsList = {
  // --- JANUARY ---
  'basil_the_great_and_gregory_nazianzen_bishops': F(1, 2, 10),
  'most_holy_name_of_jesus': F(1, 3, 12),
  'raymond_of_penyafort_priest': F(1, 7, 12),
  'hilary_of_poitiers_bishop': F(1, 13, 12),
  'anthony_of_egypt_abbot': F(1, 17, 10),
  'fabian_i_pope': F(1, 20, 12),
  'sebastian_of_milan_martyr': F(1, 20, 12),
  'agnes_of_rome_virgin': F(1, 21, 10),
  'vincent_of_saragossa_deacon': F(1, 22, 12),
  'francis_of_sales_bishop': F(1, 24, 10),
  'conversion_of_saint_paul_the_apostle': F(1, 25, 7),
  'timothy_of_ephesus_and_titus_of_crete_bishops': F(1, 26, 10),
  'angela_merici_virgin': F(1, 27, 12),
  'thomas_aquinas_priest': F(1, 28, 10),
  'john_bosco_priest': F(1, 31, 10),

  // --- FEBRUARY ---
  'presentation_of_the_lord': F(2, 2, 5),
  'blaise_of_sebaste_bishop': F(2, 3, 12),
  'ansgar_of_hamburg_bishop': F(2, 3, 12),
  'agatha_of_sicily_virgin': F(2, 5, 10),
  'paul_miki_and_companions_martyrs': F(2, 6, 10),
  'jerome_emiliani': F(2, 8, 12),
  'josephine_bakhita_virgin': F(2, 8, 12),
  'scholastica_of_nursia_virgin': F(2, 10, 10),
  'our_lady_of_lourdes': F(2, 11, 12),
  'cyril_constantine_the_philosopher_monk_and_methodius_michael_of_thessaloniki_bishop':
      F(2, 14, 10),
  'seven_holy_founders_of_the_servite_order': F(2, 17, 12),
  'peter_damian_bishop': F(2, 21, 12),
  'chair_of_saint_peter_the_apostle': F(2, 22, 7),
  'polycarp_of_smyrna_bishop': F(2, 23, 10),
  'gregory_of_narek_abbot': F(2, 27, 12),

  // --- MARCH ---
  'casimir_of_poland': F(3, 4, 12),
  'perpetua_of_carthage_and_felicity_of_carthage_martyrs': F(3, 7, 10),
  'john_of_god_duarte_cidade_religious': F(3, 8, 12),
  'frances_of_rome_religious': F(3, 9, 12),
  'patrick_of_ireland_bishop': F(3, 17, 12),
  'cyril_of_jerusalem_bishop': F(3, 18, 12),
  'turibius_of_mogrovejo_bishop': F(3, 23, 12),

  // --- APRIL ---
  'francis_of_paola_hermit': F(4, 2, 12),
  'isidore_of_seville_bishop': F(4, 4, 12),
  'vincent_ferrer_priest': F(4, 5, 12),
  'john_baptist_de_la_salle_priest': F(4, 7, 10),
  'stanislaus_of_szczepanow_bishop': F(4, 11, 10),
  'martin_i_pope': F(4, 13, 12),
  'anselm_of_canterbury_bishop': F(4, 21, 12),
  'george_of_lydda_martyr': F(4, 23, 12),
  'adalbert_of_prague_bishop': F(4, 23, 12),
  'fidelis_of_sigmaringen_priest': F(4, 24, 12),
  'mark_evangelist': F(4, 25, 7),
  'peter_chanel_priest': F(4, 28, 12),
  'louis_grignion_de_montfort_priest': F(4, 28, 12),
  'catherine_of_siena_virgin': F(4, 29, 10),
  'pius_v_pope': F(4, 30, 12),

  // --- MAY ---
  'joseph_the_worker': F(5, 1, 12),
  'athanasius_of_alexandria_bishop': F(5, 2, 10),
  'philip_and_james_apostles': F(5, 3, 7),
  'john_of_avila_priest': F(5, 10, 12),
  'nereus_of_terracina_and_achilleus_of_terracina_martyrs': F(5, 12, 12),
  'pancras_of_rome_martyr': F(5, 12, 12),
  'our_lady_of_fatima': F(5, 13, 12),
  'matthias_apostle': F(5, 14, 7),
  'john_i_pope': F(5, 18, 12),
  'bernardine_of_siena_priest': F(5, 20, 12),
  'christopher_magallanes_priest_and_companions_martyrs': F(5, 21, 12),
  'rita_of_cascia_religious': F(5, 22, 12),
  'bede_the_venerable_priest': F(5, 25, 12),
  'gregory_vii_pope': F(5, 25, 12),
  'mary_magdalene_de_pazzi_virgin': F(5, 25, 12),
  'philip_neri_priest': F(5, 26, 10),
  'augustine_of_canterbury_bishop': F(5, 27, 12),
  'paul_vi_pope': F(5, 29, 12),
  'visitation_of_mary': F(5, 31, 7),

  // --- JUNE ---
  'justin_martyr': F(6, 1, 10),
  'marcellinus_of_rome_and_peter_the_exorcist_martyrs': F(6, 2, 12),
  'charles_lwanga_and_companions_martyrs': F(6, 3, 10),
  'boniface_of_mainz_bishop': F(6, 5, 10),
  'norbert_of_xanten_bishop': F(6, 6, 12),
  'ephrem_the_syrian_deacon': F(6, 9, 12),
  'barnabas_apostle': F(6, 11, 10),
  'anthony_of_padua_priest': F(6, 13, 10),
  'romuald_of_ravenna_abbot': F(6, 19, 12),
  'aloysius_gonzaga_religious': F(6, 21, 10),
  'paulinus_of_nola_bishop': F(6, 22, 12),
  'john_fisher_bishop_and_thomas_more_martyrs': F(6, 22, 12),
  'cyril_of_alexandria_bishop': F(6, 27, 12),
  'irenaeus_of_lyon_bishop': F(6, 28, 10),
  'first_martyrs_of_the_holy_roman_church': F(6, 30, 12),

  // --- JULY ---
  'thomas_apostle': F(7, 3, 7),
  'elizabeth_of_portugal': F(7, 4, 12),
  'anthony_zaccaria_priest': F(7, 5, 12),
  'maria_goretti_virgin': F(7, 6, 12),
  'augustine_zhao_rong_priest_and_companions_martyrs': F(7, 9, 12),
  'benedict_of_nursia_abbot': F(7, 11, 10),
  'henry_ii_emperor': F(7, 13, 12),
  'camillus_de_lellis_priest': F(7, 14, 12),
  'bonaventure_of_bagnoregio_bishop': F(7, 15, 10),
  'our_lady_of_mount_carmel': F(7, 16, 12),
  'apollinaris_of_ravenna_bishop': F(7, 20, 12),
  'lawrence_of_brindisi_priest': F(7, 21, 12),
  'mary_magdalene': F(7, 22, 7),
  'bridget_of_sweden_religious': F(7, 23, 12),
  'sharbel_makhluf_priest': F(7, 24, 12),
  'james_apostle': F(7, 25, 7),
  'joachim_and_anne_parents_of_mary': F(7, 26, 10),
  'martha_of_bethany_mary_of_bethany_and_lazarus_of_bethany': F(7, 29, 10),
  'peter_chrysologus_bishop': F(7, 30, 12),
  'ignatius_of_loyola_priest': F(7, 31, 10),

  // --- AUGUST ---
  'alphonsus_mary_liguori_bishop': F(8, 1, 10),
  'eusebius_of_vercelli_bishop': F(8, 2, 12),
  'peter_julian_eymard_priest': F(8, 2, 12),
  'john_mary_vianney_priest': F(8, 4, 10),
  'dedication_of_the_basilica_of_saint_mary_major': F(8, 5, 12),
  'sixtus_ii_pope_and_companions_martyrs': F(8, 7, 12),
  'cajetan_of_thiene_priest': F(8, 7, 12),
  'dominic_de_guzman_priest': F(8, 8, 10),
  'teresa_benedicta_of_the_cross_stein_virgin': F(8, 9, 12),
  'lawrence_of_rome_deacon': F(8, 10, 7),
  'clare_of_assisi_virgin': F(8, 11, 10),
  'jane_frances_de_chantal_religious': F(8, 12, 12),
  'pontian_i_pope_and_hippolytus_of_rome_priest': F(8, 13, 12),
  'maximilian_mary_raymund_kolbe_priest': F(8, 14, 10),
  'stephen_i_of_hungary': F(8, 16, 12),
  'john_eudes_priest': F(8, 19, 12),
  'bernard_of_clairvaux_abbot': F(8, 20, 10),
  'pius_x_pope': F(8, 21, 10),
  'queenship_of_the_blessed_virgin_mary': F(8, 22, 10),
  'rose_of_lima_virgin': F(8, 23, 12),
  'bartholomew_apostle': F(8, 24, 7),
  'louis_ix_of_france': F(8, 25, 12),
  'joseph_of_calasanz_priest': F(8, 25, 12),
  'monica_of_hippo': F(8, 27, 10),
  'augustine_of_hippo_bishop': F(8, 28, 10),
  'passion_of_saint_john_the_baptist': F(8, 29, 10),

  // --- SEPTEMBER ---
  'gregory_i_the_great_pope': F(9, 3, 10),
  'nativity_of_the_blessed_virgin_mary': F(9, 8, 7),
  'peter_claver_priest': F(9, 9, 12),
  'most_holy_name_of_mary': F(9, 12, 12),
  'john_chrysostom_bishop': F(9, 13, 10),
  'exaltation_of_the_holy_cross': F(9, 14, 5),
  'our_lady_of_sorrows': F(9, 15, 10),
  'cornelius_i_pope_and_cyprian_of_carthage_bishop_martyrs': F(9, 16, 10),
  'hildegard_of_bingen_abbess': F(9, 17, 12),
  'robert_bellarmine_bishop': F(9, 17, 12),
  'januarius_i_of_benevento_bishop': F(9, 19, 12),
  'andrew_kim_tae_gon_priest_paul_chong_ha_sang_and_companions_martyrs':
      F(9, 20, 10),
  'matthew_apostle': F(9, 21, 7),
  'pius_francesco_forgione_priest': F(9, 23, 10),
  'cosmas_of_cilicia_and_damian_of_cilicia_martyrs': F(9, 26, 12),
  'vincent_de_paul_priest': F(9, 27, 10),
  'wenceslaus_i_of_bohemia_martyr': F(9, 28, 12),
  'lawrence_ruiz_and_companions_martyrs': F(9, 28, 12),
  'michael_gabriel_and_raphael_archangels': F(9, 29, 7),
  'jerome_of_stridon_priest': F(9, 30, 10),

  // --- OCTOBER ---
  'therese_of_the_child_jesus_and_the_holy_face_of_lisieux_virgin':
      F(10, 1, 10),
  'holy_guardian_angels': F(10, 2, 10),
  'francis_of_assisi': F(10, 4, 10),
  'faustina_kowalska_virgin': F(10, 5, 12),
  'bruno_of_cologne_priest': F(10, 6, 12),
  'our_lady_of_the_rosary': F(10, 7, 10),
  'denis_of_paris_bishop_and_companions_martyrs': F(10, 9, 12),
  'john_leonardi_priest': F(10, 9, 12),
  'john_xxiii_pope': F(10, 11, 12),
  'callistus_i_pope': F(10, 14, 12),
  'teresa_of_jesus_of_avila_virgin': F(10, 15, 10),
  'hedwig_of_silesia_religious': F(10, 16, 12),
  'margaret_mary_alacoque_virgin': F(10, 16, 12),
  'ignatius_of_antioch_bishop': F(10, 17, 10),
  'luke_evangelist': F(10, 18, 7),
  'john_de_brebeuf_isaac_jogues_priests_and_companions_martyrs': F(10, 19, 12),
  'paul_of_the_cross_priest': F(10, 19, 12),
  'john_paul_ii_pope': F(10, 22, 12),
  'john_of_capistrano_priest': F(10, 23, 12),
  'anthony_mary_claret_bishop': F(10, 24, 12),
  'simon_and_jude_apostles': F(10, 28, 7),

  // --- NOVEMBER ---
  'martin_de_porres_religious': F(11, 3, 12),
  'charles_borromeo_bishop': F(11, 4, 10),
  'dedication_of_the_lateran_basilica': F(11, 9, 7),
  'leo_i_the_great_pope': F(11, 10, 10),
  'martin_of_tours_bishop': F(11, 11, 10),
  'josaphat_kuntsevych_bishop': F(11, 12, 10),
  'albert_the_great_bishop': F(11, 15, 12),
  'margaret_of_scotland': F(11, 16, 12),
  'gertrude_the_great_virgin': F(11, 16, 12),
  'elizabeth_of_hungary_religious': F(11, 17, 10),
  'dedication_of_the_basilicas_of_saints_peter_and_paul_apostles':
      F(11, 18, 12),
  'presentation_of_the_blessed_virgin_mary': F(11, 21, 10),
  'cecilia_of_rome_virgin': F(11, 22, 10),
  'clement_i_pope': F(11, 23, 12),
  'columban_of_luxeuil_abbot': F(11, 23, 12),
  'andrew_dung_lac_priest_and_companions_martyrs': F(11, 24, 10),
  'catherine_of_alexandria_virgin': F(11, 25, 12),
  'andrew_apostle': F(11, 30, 7),

  // --- DECEMBER ---
  'francis_xavier_priest': F(12, 3, 10),
  'john_damascene_priest': F(12, 4, 12),
  'nicholas_of_myra_bishop': F(12, 6, 12),
  'ambrose_of_milan_bishop': F(12, 7, 10),
  'juan_diego_cuauhtlatoatzin': F(12, 9, 12),
  'our_lady_of_loreto': F(12, 10, 12),
  'damasus_i_pope': F(12, 11, 12),
  'our_lady_of_guadalupe': F(12, 12, 12),
  'lucy_of_syracuse_virgin': F(12, 13, 10),
  'john_of_the_cross_priest': F(12, 14, 10),
  'peter_canisius_priest': F(12, 21, 12),
  'john_of_kanty_priest': F(12, 23, 12),
  'thomas_becket_bishop': F(12, 29, 12),
  'sylvester_i_pope': F(12, 31, 12),
};
